name: CD
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    environment: TEST
    steps:
      - name: Run a one-line script
        run: docker ps

      - name: Run a one-line script
        run: echo $A
